node {
    def app

    stage('Clone repository') {
      

        checkout scm
    }

    stage('Update GIT') {
            script {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        //def encodedPassword = URLEncoder.encode("$GIT_PASSWORD",'UTF-8')
                        sh "git config user.email barrosoguillermo55@gmail.com"
                        sh "git config user.name GBT55"
                        //sh "git switch master"
                        sh "cat ./kustomize-sample-py-app/deployment-sample-py-app.yaml"
                        sh "sed -i 's+gbt55/sample-py-app.*+gbt55/sample-py-app:${DOCKERTAG}+g' ./kustomize-sample-py-app/deployment-sample-py-app.yaml"
                        sh "cat ./kustomize-sample-py-app/deployment-sample-py-app.yaml"
                        sh "git add ."
                        sh "git commit -m 'Done by Jenkins Job updatemanifest: ${env.BUILD_NUMBER}'"
                        sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/${GIT_USERNAME}/kubernetesmanifest.git HEAD:main"
      }
    }
  }
}
}